Repository 2020-1-DTool/dTool, pull requests merged in 2020-06, with the labels that each got.

#23 Contador execucao
  src/containers/CardDescription.tsx
  src/screens/CarouselScreen.tsx
  tsconfig.json
Labels: la-casa-de-papel, ready-for-review

#24 Atualiza contagens em andamento no evento de `focus`
  src/screens/CarouselScreen.tsx
  src/screens/EmptyScreen.tsx
  src/services/timerFunction.ts
Labels: la-casa-de-papel, ready-for-review

#25 # [01] Os botões exibidos devem refletir no estado atual do card selecionado
  package-lock.json
  package.json
  src/App.tsx
  src/components/CardRow.tsx
  src/containers/CardDescription.tsx
  src/containers/Carousel.tsx
  src/screens/CarouselScreen.tsx
  src/screens/ChooseActivity.tsx
  src/screens/ListPatient.tsx
  src/services/asyncStorageAdapter.ts
  src/services/timerFunction.ts
  src/services/types.ts
  src/store/actions/execution.ts
  src/store/index.ts
  src/store/reducers/execution.ts
  src/store/reducers/index.ts
Labels: la-casa-de-papel, ready-for-review

#27 B04 - Exportação do relatório para gestão
  android/app/build.gradle
  android/app/src/main/java/com/dtool/MainApplication.java
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/ButtonSecundary.tsx
  src/screens/HospitalInformation.tsx
  src/services/appService.ts
Labels: enhancement, ready-for-review

#28 Fazer uma contagem de tempos dinâmica para a tela de execuções
  src/App.tsx
  src/components/CardRow.tsx
  src/containers/CardDescription.tsx
  src/screens/CarouselScreen.tsx
  src/screens/EmptyScreen.tsx
  src/screens/HospitalInformation.tsx
  src/screens/ListPatient.tsx
  src/services/appService.ts
  src/services/localStorage.ts
  src/services/timerFunction.ts
  src/services/types.ts
  src/store/actions/execution.ts
  src/store/reducers/execution.ts
Labels: ready-for-review

#31 Resolvendo alguns bugs
  src/screens/CarouselScreen.tsx
  src/services/appService.ts
Labels: ready-for-review

#29 Relatórios
  package-lock.json
  package.json
  src/App.tsx
  src/components/ButtonNavigation.tsx
  src/components/Report.tsx
  src/components/index.ts
  src/screens/ChooseRole.tsx
  src/screens/HospitalInformation.tsx
  src/screens/ReportsScreen.tsx
  src/screens/index.ts
  src/services/appService.ts
  src/services/types.ts
Labels: ready-for-review

#33 Download de xlsx - Android
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dtool/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/dTool/Info.plist
  package-lock.json
  package.json
  src/services/appService.ts
Labels: ready-for-review

#34 Ajuste - Adiciona endDate a execucao finalizada e enviada para backend
  src/services/appService.ts
  src/services/timerFunction.ts
  src/services/types.ts
Labels: ready-for-review
