Repository 2020-1-DTool/dTool, pull requests merged in 2020-05, with the labels that each got.

#1 [Gestão] Atualização da tela de informações do hospital
  src/screens/HospitalInformation.tsx
  src/services/localStorage.ts
Labels: Squad X_MEN, ready-for-review

#3 DividaTecnica- Deixa todo o campo da lista selecionavel
  src/components/BasicList.tsx
Labels: Vingadores, ready-for-review

#5 Input para digitar código do hospital pode pular direto para a proxima letra.
  src/components/InputCode.tsx
  src/containers/CodeEntry.tsx
Labels: enhancement, ready-for-review

#2 Botão de Soma no Carousel
  src/App.tsx
  src/containers/Carousel.tsx
  src/screens/CarouselScreen.tsx
  src/screens/ChooseActivity.tsx
  src/screens/ChooseTechnology.tsx
  src/screens/EmptyScreen.tsx
Labels: guardioes-da-galaxia, ready-for-review

#6 Dívida técnica: conteúdo excedendo tamanho da tela
  src/components/ButtonPrimary.tsx
  src/components/ButtonSecundary.tsx
  src/screens/AddPatient.tsx
  src/screens/HospitalCode.tsx
  src/screens/HospitalInformation.tsx
Labels: bug, ready-for-review

#4 Componente botao contagem
  src/components/ButtonExecutions.tsx
  src/components/index.ts
  src/screens/HospitalInformation.tsx
Labels: guardioes-da-galaxia, ready-for-review

#7 App Gestão: Tela de Listagem de Tecnologia
  package-lock.json
  src/App.tsx
  src/components/BasicList.tsx
  src/containers/admin/TechnologyList.tsx
  src/containers/index.ts
  src/screens/HospitalInformation.tsx
  src/screens/admin/ListTechnology.tsx
  src/screens/index.ts
  src/services/localStorage.ts
  src/services/types.ts
Labels: Squad X_MEN, ready-for-review

#8 Tela "Nova tecnologia"
  src/App.tsx
  src/components/ButtonExecutions.tsx
  src/containers/Carousel.tsx
  src/containers/admin/TechnologyList.tsx
  src/screens/admin/AddTechnology.tsx
  src/screens/admin/ListTechnology.tsx
  src/screens/index.ts
Labels: Squad X_MEN, ready-for-review

#10 App Gestão: Tela de Tecnologia Padrão
  src/App.tsx
  src/components/BasicList.tsx
  src/screens/admin/AddTechnology.tsx
  src/screens/admin/DocList.tsx
  src/screens/index.ts
  src/services/types.ts
Labels: Squad X_MEN, ready-for-review

#9 Timer function
  package-lock.json
  package.json
  src/App.tsx
  src/screens/EmptyScreen.tsx
  src/screens/HospitalInformation.tsx
  src/services/asyncStorageAdapter.ts
  src/services/localStorage.ts
  src/services/timerFunction.ts
  src/services/types.ts
Labels: Vingadores, guardioes-da-galaxia, ready-for-review

#11 Abrir descrição de atividade ao clicar em um card do Carousel e ao clicar e um item na lista de atividades adicionar no carousel
  src/components/CardRow.tsx
  src/containers/Carousel.tsx
  src/screens/CarouselScreen.tsx
  src/screens/ChooseActivity.tsx
  src/screens/ChooseTechnology.tsx
  src/screens/ListPatient.tsx
  src/screens/StartScreen.tsx
  src/services/appService.ts
  src/services/asyncStorageAdapter.ts
  src/services/localStorage.ts
  src/services/types.ts
Labels: guardioes-da-galaxia, ready-for-review

#13 Descrição da atividade na tela de Contagem de Tempos
  src/App.tsx
  src/containers/CardDescription.tsx
  src/containers/index.ts
  src/screens/CarouselScreen.tsx
  src/screens/ChooseRole.tsx
  src/services/localStorage.ts
  src/services/types.ts
Labels: guardioes-da-galaxia, ready-for-review

#14 Integracao - Add function to get status of an execution
  src/services/timerFunction.ts
Labels: Vingadores, ready-for-review
